#!/usr/bin/env python3
"""Regenerate the synthetic replay example, data/replay/example_trace.jsonl.

Usage:
    python scripts/make_example_trace.py [--output data/replay/example_trace.jsonl]

The example trace is synthetic but format-identical to a live-recorded
results/<run>/trace.jsonl: the deterministic rule policy answers every
inference request, latencies are seeded pseudo-random values, and two
deadline misses (latency > the 300 ms default deadline) plus one malformed
response are injected at fixed request ids - so a replayed run exercises the
fallback, late-response-discard, and validation paths without a model server.

The trace is produced by actually executing the stop-sign scenario (fast
mode) with a synthetic backend, so the recorded snapshots are exactly the
ones a replay run observes and `replay_mismatch_count` stays 0. The script
is deterministic: rerunning it reproduces the file byte for byte.
"""

from __future__ import annotations

import argparse
import random
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from agentic_driving_coach.backends.base import InferenceBackend  # noqa: E402
from agentic_driving_coach.config import RunConfig  # noqa: E402
from agentic_driving_coach.messages import (  # noqa: E402
    CoachToken,
    InferenceRequest,
    InferenceResult,
)
from agentic_driving_coach.parsing import parse_coach_output  # noqa: E402
from agentic_driving_coach.policies import stop_sign_policy  # noqa: E402
from agentic_driving_coach.scenario import run_scenario  # noqa: E402

SEED = 20260811
LATENCY_RANGE_MS = (120.0, 240.0)
#: request_id -> injected latency (ms), above the 300 ms default deadline, so
#: the replayed run records a deadline miss and a late discarded response.
MISS_LATENCIES_MS = {8: 429.383, 22: 383.081}
#: request_id -> injected raw response violating the TOKEN|Message contract.
MALFORMED_RESPONSES = {14: "I think you should slow down a little."}

HEADER = """\
# Example inference trace for the ReplayCoach (JSON Lines; '#' lines are comments).
# Synthetic but format-identical to a live-recorded trace: rule-policy tokens with
# seeded pseudo-latencies, two deadline misses (latency > 300 ms) and one malformed
# response, so a replayed run exercises fallback and late-response handling.
# Provenance: generated by scripts/make_example_trace.py (see docs/provenance.md).
# A live run writes the same format to results/<run>/trace.jsonl, which can be
# replayed with --coach replay --trace ...
"""


class SyntheticBackend(InferenceBackend):
    """Rule-policy answers with seeded pseudo-latencies and injected faults."""

    name = "synthetic-example"
    model_label = "synthetic-example"
    is_async = False

    def __init__(self, policy_params) -> None:
        self._params = policy_params
        self._rng = random.Random(SEED)

    def compute(self, request: InferenceRequest) -> InferenceResult:
        latency = MISS_LATENCIES_MS.get(
            request.request_id, round(self._rng.uniform(*LATENCY_RANGE_MS), 3)
        )
        raw = MALFORMED_RESPONSES.get(request.request_id)
        if raw is None:
            token, message = stop_sign_policy(
                request.snapshot.distance_m, request.snapshot.velocity_mps, self._params
            )
            raw = f"{token.value}|{message}"
        parsed = parse_coach_output(raw)
        return InferenceResult(
            request_id=request.request_id,
            raw_response=raw,
            token=parsed.token if parsed.token is not None else CoachToken.NONE,
            message=parsed.message,
            latency_ms=latency,
            malformed=parsed.malformed,
        )

    def close(self) -> None:
        pass


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    parser.add_argument(
        "--output",
        type=Path,
        default=REPO / "data" / "replay" / "example_trace.jsonl",
        help="where to write the trace (default: data/replay/example_trace.jsonl)",
    )
    args = parser.parse_args()

    with tempfile.TemporaryDirectory() as tmp:
        cfg = RunConfig(output_dir=Path(tmp), fast=True, run_id="example-trace")
        backend = SyntheticBackend(cfg.scenario.policy)
        summary, _ = run_scenario(cfg, argv=["make_example_trace"], backend=backend)
        trace_text = (Path(tmp) / "trace.jsonl").read_text(encoding="utf-8")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(HEADER + trace_text, encoding="utf-8")
    print(f"wrote {args.output}")
    print(
        f"  requests={summary.inference_requests} "
        f"misses={summary.deadline_miss_count} "
        f"late_discarded={summary.late_response_count} "
        f"malformed={summary.malformed_response_count} "
        f"fallbacks={summary.fallback_count} "
        f"stopped={summary.stopped} "
        f"v_at_stop_line={summary.velocity_at_stop_line_mps}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
